### PR TITLE
track multiple concurrent requests

### PR DESCRIPTION
**Pull request by miyura**

### CODE REVIEW

**Comment by MurhafSousli** [comment]
Hi @miyura don't you think it already tracks multiple concurrent requests

**Comment by miyura** [comment]
Hi MurhafSousli,

If there are concurrent inflight request the progress bar complete as soon
as the first response complete. It doesnt wait until rest of the inflight
responses complete.

On Dec 17, 2017 4:11 PM, "Murhaf Sousli" <notifications@github.com> wrote:

Hi @miyura <https://github.com/miyura> don't you think it already tracks
multiple concurrent requests

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MurhafSousli/ngx-progressbar/pull/105#issuecomment-352289905>,
or mute the thread

**Comment by miyura** [comment]
Hi @MurhafSousli, Do you have any suggestions to achieve this?

**Comment by MurhafSousli** [comment]
Hi @miyura 
As far as I know, the `finalize` operator on the `HttpHandler` is triggered once all the current requests are done
```ts
return next.handle(req).pipe(finalize(() => {
    // all requests are done
 });
```

**Comment by miyura** [comment]
Hi @MurhafSousli, please try the "Test Http Client" in this stackblitz

https://stackblitz.com/edit/ngx-progressbar-j1wbsp

**Comment by MurhafSousli** [comment]
@miyura You are right, thanks a lot

**Pull request merged**
