### PR TITLE
ci: test Node.js 8, 10 and 11

### PR DESCRIPTION
**Pull request by DanielRuf**
We should test all current LTS branches and also current stable.

See https://github.com/nodejs/Release/blob/master/README.md

### CODE REVIEW

**Comment by DanielRuf** [comment]
So Node.js 6 is not supported which we should make clear in the `engines` field of the package.json file.

**Comment by MurhafSousli** [comment]
Hi @DanielRuf sorry for late response. If it works on node 8 then it should be fine, the CI is already slow, I think adding this will make it even slower.

**Comment by DanielRuf** [comment]
> Hi @DanielRuf sorry for late response. If it works on node 8 then it should be fine, the CI is already slow, I think adding this will make it even slower.

They mostly run in parallel (at least 3). 8, 10 and 11 / stable should be generally tested (fail early).

**Comment by DanielRuf** [comment]
Shall I remove 6 and shall we add `engines.node >= 8.0.0` in the next major release?

**Comment by MurhafSousli** [comment]
Yes, I think it will better without 6

**Comment by DanielRuf** [comment]
Done.

**Comment by DanielRuf** [comment]
bildschirmfoto 2018-11-28 um 11 35 08

**Comment by DanielRuf** [comment]
https://travis-ci.org/MurhafSousli/ngx-progressbar/jobs/460706653#L458

I think this is a bit outdated.

**Comment by MurhafSousli** [comment]
@DanielRuf Thanks for the PR!

> I think this is a bit outdated.

 I don't know where that yarn version is defined, Do you know how to fix it?

**Comment by DanielRuf** [comment]
> I don't know where that yarn version is defined, Do you know how to fix it?

Generally this is the version that is used by / shipping with Travis CI.
See https://travis-ci.org/angular/angular/jobs/460481892#L553 and https://travis-ci.org/angular/angular/jobs/460481892#L22

They use the latest release of yarn but the build is from December 2017. See https://travis-ci.org/angular/angular/jobs/460481892#L15

https://github.com/travis-ci/travis-cookbooks/pull/935/files

**Comment by DanielRuf** [comment]
I've already upgraded yarn in the last commit so builds are faster with the current version now.

**Pull request merged**
