### PR TITLE
README update with HttpClient instructions

### PR DESCRIPTION
**Pull request by zcsongor**

### CODE REVIEW

**Comment by denniseffing** [comment]
The idea behind the automatic loading bar (as far as I understand) is that the user doesn't have to write many lines of boilerplate code in his own application. 

You should implement a new class like NgProgressBrowserXhr but here you won't extend BrowserXhr from `@angular/http` but from `@angular/common/http`. After that, the user of ngx-progressbar should be able to use it like this:

 ```ts
import { BrowserXhr } from '@angular/http';
import { <new classname here> } from 'ngx-progressbar';

@NgModule({
  providers: [
    // ...
    { provide: BrowserXhr, useClass: <new classname here> } ,
  ],
  imports: [
    // ...
    NgProgressModule
  ]
})
```

This results in just a minor modification for the user if he wants to switch from `@angular/http` to `@angular/common/http`.

**Comment by MurhafSousli** [comment]
@denniseffing is right, I was expecting a PR for a plug! but this is just a README update!

**Comment by zcsongor** [comment]
Yes, as I mentioned earlier [here](https://github.com/MurhafSousli/ngx-progressbar/issues/57). If I have time, I'll do the plug.

**Comment by zcsongor** [comment]
@denniseffing Instead of extending BrowserXhr I'd create a PR with the exact copy of HttpInterceptor which is in the README, and I'd add it to the modules' providers' list. It has been made for cases just like this. What do you think?

**Comment by denniseffing** [comment]
That is completely fine and to be honest, I thought the exact same thing after I looked deeper into the new http client (didn't use it before).

Even though it would be desirable if the configuration for the automatig loading bar wouldn't be different for two different http clients, I think that using something as it was intended should be given more weight than a unified configuration.

**Comment by zcsongor** [comment]
Agree. If that sounds okay to you as well @MurhafSousli I'll create a PR.

**Comment by MurhafSousli** [comment]
Thanks @denniseffing @zcsongor, I have added HttpClient plug in 2.0.4

**Pull request closed without merging**
